[features]
seeds = false
skip-lint = false
[programs.localnet]
speedrun_game_jam = "HGPJjX9fXH5dwJ8MkJTfmKbzUF7nLECjrB3ovts4DuBb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/kyle/.config/solana/id.json"

[scripts]
test = "yarn run jest"
