[features]
seeds = false
skip-lint = false
[programs.localnet]
# speedrun_game_jam = "HGPJjX9fXH5dwJ8MkJTfmKbzUF7nLECjrB3ovts4DuBb"
nebula_drifter = "9M6Rorip8xtNHS19hJyH6ECfpKwPKAn8RQMW8uhHdYYV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/kyle/.config/solana/id.json"

[scripts]
test = "yarn run jest"
